"""updated_methods

Revision ID: 649eac6ae8d2
Revises: a3b1c9d4e6f7
Create Date: 2026-08-13 15:25:10.772712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649eac6ae8d2'
down_revision = 'a3b1c9d4e6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_role_role_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('user_roles_UserRole_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_roles_UserRole_role_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_role_user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'roles', ['user_role_role_id'], ['role_id'])
        batch_op.drop_column('UserRole_role_id')
        batch_op.drop_column('UserRole_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UserRole_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('UserRole_role_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_roles_UserRole_role_id_fkey'), 'roles', ['UserRole_role_id'], ['role_id'])
        batch_op.create_foreign_key(batch_op.f('user_roles_UserRole_user_id_fkey'), 'users', ['UserRole_user_id'], ['user_id'])
        batch_op.drop_column('user_role_role_id')
        batch_op.drop_column('user_role_user_id')

    # ### end Alembic commands ###
