"""test

Revision ID: 76c56ea45e73
Revises: c8ef17d58f9e
Create Date: 2026-08-11 12:47:48.987232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76c56ea45e73'
down_revision = 'c8ef17d58f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_articles',
    sa.Column('knowledge_article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_article_title', sa.String(length=100), nullable=False),
    sa.Column('knowledge_article_content', sa.Text(), nullable=False),
    sa.Column('knowledge_article_category_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_article_author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_article_author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['knowledge_article_category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('knowledge_article_id')
    )
    op.create_table('satisfaction_surveys',
    sa.Column('satisfaction_survey_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satisfaction_survey_rating', sa.Integer(), nullable=False),
    sa.Column('satisfaction_survey_comment', sa.Text(), nullable=True),
    sa.Column('satisfaction_survey_ticket_id', sa.Integer(), nullable=False),
    sa.Column('satisfaction_survey_client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('satisfaction_survey_rating >= 1 AND satisfaction_survey_rating <= 5', name='Rating_range'),
    sa.ForeignKeyConstraint(['satisfaction_survey_client_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['satisfaction_survey_ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('satisfaction_survey_id'),
    sa.UniqueConstraint('satisfaction_survey_ticket_id')
    )
    op.create_table('ticket_status_histories',
    sa.Column('ticket_status_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_status_history_ticket_id', sa.Integer(), nullable=True),
    sa.Column('ticket_status_history_user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_status_history_old_status', sa.String(length=16), nullable=False),
    sa.Column('ticket_status_history_new_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_status_history_ticket_id'], ['tickets.ticket_id'], ),
    sa.ForeignKeyConstraint(['ticket_status_history_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_status_history_id')
    )
    op.drop_table('satisfactionsurveys')
    op.drop_table('knowledgearticles')
    op.drop_table('ticketstatushistories')
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_purchase_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('equipment_site_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('equipment_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('equipments_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('equipments_site_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['equipment_user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'sites', ['equipment_site_id'], ['site_id'])
        batch_op.drop_column('equipment_purchasedate')
        batch_op.drop_column('site_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervention_ticket_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('intervention_technician_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('interventions_ticket_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('interventions_technician_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['intervention_technician_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'tickets', ['intervention_ticket_id'], ['ticket_id'])
        batch_op.drop_column('ticket_id')
        batch_op.drop_column('technician_id')

    with op.batch_alter_table('ticket_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_tag_tag_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ticket_tag_ticket_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('ticket_tags_ticket_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ticket_tags_tag_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['ticket_tag_tag_id'], ['tag_id'])
        batch_op.create_foreign_key(None, 'tickets', ['ticket_tag_ticket_id'], ['ticket_id'])
        batch_op.drop_column('tag_id')
        batch_op.drop_column('ticket_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ticket_tags_tag_id_fkey'), 'tags', ['tag_id'], ['tag_id'])
        batch_op.create_foreign_key(batch_op.f('ticket_tags_ticket_id_fkey'), 'tickets', ['ticket_id'], ['ticket_id'])
        batch_op.drop_column('ticket_tag_ticket_id')
        batch_op.drop_column('ticket_tag_tag_id')

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technician_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('interventions_technician_id_fkey'), 'users', ['technician_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('interventions_ticket_id_fkey'), 'tickets', ['ticket_id'], ['ticket_id'])
        batch_op.drop_column('intervention_technician_id')
        batch_op.drop_column('intervention_ticket_id')

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('equipment_purchasedate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('equipments_site_id_fkey'), 'sites', ['site_id'], ['site_id'])
        batch_op.create_foreign_key(batch_op.f('equipments_user_id_fkey'), 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('equipment_user_id')
        batch_op.drop_column('equipment_site_id')
        batch_op.drop_column('equipment_purchase_date')

    op.create_table('ticketstatushistories',
    sa.Column('ticketstatushistory_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticketstatushistory_ticket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticketstatushistory_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticketstatushistory_old_status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('ticketstatushistory_new_status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticketstatushistory_ticket_id'], ['tickets.ticket_id'], name=op.f('ticketstatushistories_ticketstatushistory_ticket_id_fkey')),
    sa.ForeignKeyConstraint(['ticketstatushistory_user_id'], ['users.user_id'], name=op.f('ticketstatushistories_ticketstatushistory_user_id_fkey')),
    sa.PrimaryKeyConstraint('ticketstatushistory_id', name=op.f('ticketstatushistories_pkey'))
    )
    op.create_table('knowledgearticles',
    sa.Column('knowledgearticles_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('knowledgearticles_title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('knowledgearticles_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], name=op.f('knowledgearticles_author_id_fkey')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('knowledgearticles_category_id_fkey')),
    sa.PrimaryKeyConstraint('knowledgearticles_id', name=op.f('knowledgearticles_pkey'))
    )
    op.create_table('satisfactionsurveys',
    sa.Column('satisfactionsurveys_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('satisfactionsurveys_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('satisfactionsurveys_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.CheckConstraint('satisfactionsurveys_rating >= 1 AND satisfactionsurveys_rating <= 5', name=op.f('Rating_range')),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], name=op.f('satisfactionsurveys_client_id_fkey')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], name=op.f('satisfactionsurveys_ticket_id_fkey')),
    sa.PrimaryKeyConstraint('satisfactionsurveys_id', name=op.f('satisfactionsurveys_pkey')),
    sa.UniqueConstraint('ticket_id', name=op.f('satisfactionsurveys_ticket_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('ticket_status_histories')
    op.drop_table('satisfaction_surveys')
    op.drop_table('knowledge_articles')
    # ### end Alembic commands ###
