"""init

Revision ID: c8ef17d58f9e
Revises: 
Create Date: 2026-08-11 12:04:07.057985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ef17d58f9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('intervention_types',
    sa.Column('intervention_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intervention_type_name', sa.String(length=64), nullable=False),
    sa.Column('intervention_type_description', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('intervention_type_id'),
    sa.UniqueConstraint('intervention_type_name')
    )
    op.create_table('priorities',
    sa.Column('priority_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priority_name', sa.String(length=100), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('priority_delay_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('priority_id'),
    sa.UniqueConstraint('priority_name')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_role_name'), ['role_name'], unique=True)

    op.create_table('sites',
    sa.Column('site_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('site_address', sa.String(length=255), nullable=True),
    sa.Column('site_city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=False),
    sa.Column('tag_color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=80), nullable=False),
    sa.Column('team_description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_team_name'), ['team_name'], unique=True)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_username', sa.String(length=80), nullable=False),
    sa.Column('user_firstname', sa.String(length=64), nullable=False),
    sa.Column('user_lastname', sa.String(length=64), nullable=False),
    sa.Column('user_email', sa.String(length=128), nullable=False),
    sa.Column('user_password', sa.String(length=256), nullable=False),
    sa.Column('user_team_id', sa.Integer(), nullable=True),
    sa.Column('user_site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['user_site_id'], ['sites.site_id'], ),
    sa.ForeignKeyConstraint(['user_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_user_email'), ['user_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_username'), ['user_username'], unique=True)

    op.create_table('equipments',
    sa.Column('equipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.String(length=80), nullable=False),
    sa.Column('equipment_serial', sa.String(length=100), nullable=False),
    sa.Column('equipment_purchasedate', sa.DateTime(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('equipment_id'),
    sa.UniqueConstraint('equipment_serial')
    )
    op.create_table('knowledgearticles',
    sa.Column('knowledgearticles_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledgearticles_title', sa.String(length=100), nullable=False),
    sa.Column('knowledgearticles_content', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('knowledgearticles_id')
    )
    op.create_table('user_roles',
    sa.Column('UserRole_user_id', sa.Integer(), nullable=False),
    sa.Column('UserRole_role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['UserRole_role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['UserRole_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('UserRole_user_id', 'UserRole_role_id')
    )
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_title', sa.String(length=64), nullable=False),
    sa.Column('ticket_description', sa.String(length=255), nullable=True),
    sa.Column('ticket_status', sa.String(length=64), nullable=False),
    sa.Column('ticket_due_date', sa.DateTime(), nullable=True),
    sa.Column('ticket_author_id', sa.Integer(), nullable=False),
    sa.Column('ticket_technician_id', sa.Integer(), nullable=True),
    sa.Column('ticket_category_id', sa.Integer(), nullable=False),
    sa.Column('ticket_priority_id', sa.Integer(), nullable=False),
    sa.Column('ticket_equipment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['ticket_equipment_id'], ['equipments.equipment_id'], ),
    sa.ForeignKeyConstraint(['ticket_priority_id'], ['priorities.priority_id'], ),
    sa.ForeignKeyConstraint(['ticket_technician_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('attachment_ticket_id', sa.Integer(), nullable=True),
    sa.Column('attachment_author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['attachment_ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_attachment_filename'), ['attachment_filename'], unique=True)

    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_content', sa.String(length=1024), nullable=True),
    sa.Column('comment_author_id', sa.Integer(), nullable=True),
    sa.Column('comment_ticket_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['comment_author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['comment_ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('interventions',
    sa.Column('intervention_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intervention_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intervention_duration', sa.Integer(), nullable=False),
    sa.Column('intervention_report', sa.String(length=256), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('intervention_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['intervention_type_id'], ['intervention_types.intervention_type_id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('intervention_id')
    )
    op.create_table('satisfactionsurveys',
    sa.Column('satisfactionsurveys_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satisfactionsurveys_rating', sa.Integer(), nullable=False),
    sa.Column('satisfactionsurveys_comment', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('satisfactionsurveys_rating >= 1 AND satisfactionsurveys_rating <= 5', name='Rating_range'),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('satisfactionsurveys_id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('ticket_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'ticket_id')
    )
    op.create_table('ticketstatushistories',
    sa.Column('ticketstatushistory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticketstatushistory_ticket_id', sa.Integer(), nullable=True),
    sa.Column('ticketstatushistory_user_id', sa.Integer(), nullable=True),
    sa.Column('ticketstatushistory_old_status', sa.String(length=16), nullable=False),
    sa.Column('ticketstatushistory_new_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['ticketstatushistory_ticket_id'], ['tickets.ticket_id'], ),
    sa.ForeignKeyConstraint(['ticketstatushistory_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ticketstatushistory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticketstatushistories')
    op.drop_table('ticket_tags')
    op.drop_table('satisfactionsurveys')
    op.drop_table('interventions')
    op.drop_table('comments')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_attachment_filename'))

    op.drop_table('attachments')
    op.drop_table('tickets')
    op.drop_table('user_roles')
    op.drop_table('knowledgearticles')
    op.drop_table('equipments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_username'))
        batch_op.drop_index(batch_op.f('ix_users_user_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_team_name'))

    op.drop_table('teams')
    op.drop_table('tags')
    op.drop_table('sites')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_role_name'))

    op.drop_table('roles')
    op.drop_table('priorities')
    op.drop_table('intervention_types')
    op.drop_table('categories')
    # ### end Alembic commands ###
